train:
  _target_: src.datasets.VCTKDataset
  dataset_split_file: "src/VCTK_split/training.txt"
  vctk_wavs_dir: /Users/polinakadeyshvili/AMI/4_course/diplom/hifi++_dla/16khz
  high_sampling_rate: 16000
  low_sampling_rate: 4000
  segment_size: 32768
  device: ${trainer.device}
  lowpass: "default"
  split: False
val:
  _target_: src.datasets.VCTKDataset
  dataset_split_file: "src/VCTK_split/validation.txt"
  vctk_wavs_dir: /Users/polinakadeyshvili/AMI/4_course/diplom/hifi++_dla/16khz
  high_sampling_rate: 16000
  low_sampling_rate: 4000
  segment_size: 32768
  device: ${trainer.device}
  lowpass: "default"
  split: False
