train:
  _target_: src.datasets.VCTKDataset
  dataset_split_file: "data/training.txt"
  vctk_wavs_dir: /kaggle/input/datasets/alleksey5/wav-vctk/VCTK_wav
  high_sampling_rate: 16000
  low_sampling_rate: 4000
  segment_size: 32768
  device: ${trainer.device}
  lowpass: "default"
  split: False
val:
  _target_: src.datasets.VCTKDataset
  dataset_split_file: "data/validation.txt"
  vctk_wavs_dir: /kaggle/input/datasets/alleksey5/wav-vctk/VCTK_wav
  high_sampling_rate: 16000
  low_sampling_rate: 4000
  segment_size: 32768
  device: ${trainer.device}
  lowpass: "default"
  split: False
