test:
  _target_: src.datasets.vctk_dataset.VCTKDataset
  dataset_split_file: "/content/Diploma_repo/data/vctk_test.txt"
  vctk_wavs_dir: "/content/Diploma_repo/data/VCTK/wavs"
  segment_size: 8192
  sampling_rate: 16000
  window: 4096
  split: True
  instance_transforms: null