train:
  _target_: src.datasets.vctk_dataset.VCTKDataset
  dataset_split_file: "/content/Diploma_repo/data/training_filtered.txt"   # или свой файл
  vctk_wavs_dir: "/content/Diploma_repo/data/VCTK_wav"
  segment_size: 8192
  sampling_rate: 16000
  window: 4096
  split: True
  shuffle: True
  limit: 1
  instance_transforms: ${transforms.instance_transforms.train}

val:
  _target_: src.datasets.vctk_dataset.VCTKDataset
  dataset_split_file: "/content/Diploma_repo/data/validation_filtered.txt"
  vctk_wavs_dir: "/content/Diploma_repo/data/VCTK_wav"
  segment_size: 8192
  sampling_rate: 16000
  window: 4096
  split: True
  shuffle: False
  limit: 1
  instance_transforms: ${transforms.instance_transforms.inference}
