train:
  - _target_: src.metrics.SI_SDR
    name: "SI_SDR"
    use_pit: false

  - _target_: src.metrics.SNR
    name: "SNR"
    use_pit: false

inference:
  - _target_: src.metrics.SI_SDR
    name: "SI_SDR"
    use_pit: false

  - _target_: src.metrics.SNR
    name: "SNR"
    use_pit: false

  - _target_: src.metrics.STOI
    name: "STOI"
    use_pit: false

  - _target_: src.metrics.PESQ
    name: "PESQ"
    use_pit: false
