defaults:
  - model: hifiplusplus
  - metrics: vctk_dataset
  - datasets: vctk_dataset
  - dataloader: example
  - transforms: example_only_instance
  - writer: cometml
  - _self_

loss_function:
  _target_: torch.nn.L1Loss

optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 1e-3
  pct_start: 0.1
  steps_per_epoch: 1
  epochs: 1 
  anneal_strategy: cos

trainer:
  device_tensors: ["audio", "tg_audio"]
  device: auto
  n_epochs: 3
  log_step: 3
  save_period: 3
  save_dir: "saved"
  seed: 1
  override: True
  monitor: "off"