defaults:
  - model: hifiplusplus_dfnetpost
  - writer: cometml
  - metrics: vctk_dataset
  - datasets: vctk_dataset
  - dataloader: example
  - _self_

gen_optimizer:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas: [0.8, 0.99]
  weight_decay: 0.01

disc_optimizer:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas: [0.8, 0.99]
  weight_decay: 0.01

gen_lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.999

disc_lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.999

loss_function:
  _target_: src.loss.HiFiGANLoss

optimizer:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas: [0.8, 0.99]
  weight_decay: 0.01

lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.999

trainer:
  log_step: 1
  n_epochs: 1
  epoch_len: 2
  device_tensors: ["wav_lr", "wav_hr"]
  resume_from: null
  device: auto
  override: True
  monitor: "off"
  save_period: 1000000
  early_stop: ${trainer.n_epochs}
  save_dir: "saved_dir"
  seed: 1
  max_grad_norm: 10
